"""add_registrations_table

Revision ID: 0ae8f43ee202
Revises: 16d85ef96522
Create Date: 2026-03-02 20:48:47.574779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel.sql.sqltypes import AutoString


# revision identifiers, used by Alembic.
revision: str = '0ae8f43ee202'
down_revision: Union[str, Sequence[str], None] = '16d85ef96522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "registrations",
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column(
            "student_name", AutoString(length=255), nullable=False
        ),
        sa.Column(
            "parent_name", AutoString(length=255), nullable=False
        ),
        sa.Column(
            "parent_email", AutoString(length=255), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "CONFIRMED", "CANCELLED", name="registrationstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_registration_trip_id"), "registrations", ["trip_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_registration_trip_id"), table_name="registrations")
    op.drop_table("registrations")
    # ### end Alembic commands ###
