"""add_trips_table

Revision ID: 16d85ef96522
Revises: f8deaa7682e5
Create Date: 2026-03-02 20:48:43.532675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel.sql.sqltypes import AutoString


# revision identifiers, used by Alembic.
revision: str = '16d85ef96522'
down_revision: Union[str, Sequence[str], None] = 'f8deaa7682e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trips",
        sa.Column(
            "title", AutoString(length=255), nullable=False
        ),
        sa.Column(
            "description", AutoString(length=1000), nullable=True
        ),
        sa.Column(
            "location", AutoString(length=500), nullable=False
        ),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("max_students", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trip_school_id"), "trips", ["school_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trip_school_id"), table_name="trips")
    op.drop_table("trips")
    # ### end Alembic commands ###
