"""add_payments_table

Revision ID: f16277d6afd4
Revises: 0ae8f43ee202
Create Date: 2026-03-02 20:48:51.420825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel.sql.sqltypes import AutoString


# revision identifiers, used by Alembic.
revision: str = 'f16277d6afd4'
down_revision: Union[str, Sequence[str], None] = '0ae8f43ee202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("registration_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SUCCESS", "FAILED", name="paymentstatus"),
            nullable=False,
        ),
        sa.Column(
            "transaction_id",
            AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "error_message",
            AutoString(length=1000),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["registration_id"],
            ["registrations.id"],
            ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_registration_id"), "payments", ["registration_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_registration_id"), table_name="payments")
    op.drop_table("payments")
    # ### end Alembic commands ###
