// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_login_access_token_api_v1_users_login_access_token_post
 */
export type BodyLoginAccessTokenApiV1UsersLoginAccessTokenPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * PaymentProcess
 */
export type PaymentProcess = {
    /**
     * Registration Id
     */
    registration_id: string;
    /**
     * Card Number
     */
    card_number: string;
    /**
     * Expiry Date
     */
    expiry_date: string;
    /**
     * Cvv
     */
    cvv: string;
};

/**
 * PaymentPublic
 */
export type PaymentPublic = {
    /**
     * Registration Id
     */
    registration_id: string;
    /**
     * Amount
     */
    amount: string;
    /**
     * Id
     */
    id: string;
    status: PaymentStatus;
    /**
     * Transaction Id
     */
    transaction_id?: string | null;
    /**
     * Error Message
     */
    error_message?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * PaymentStatus
 */
export type PaymentStatus = 'pending' | 'success' | 'failed';

/**
 * RegistrationCreate
 */
export type RegistrationCreate = {
    /**
     * Trip Id
     */
    trip_id: string;
    /**
     * Student Name
     */
    student_name: string;
    /**
     * Parent Name
     */
    parent_name: string;
    /**
     * Parent Email
     */
    parent_email: string;
};

/**
 * RegistrationPublic
 */
export type RegistrationPublic = {
    /**
     * Trip Id
     */
    trip_id: string;
    /**
     * Student Name
     */
    student_name: string;
    /**
     * Parent Name
     */
    parent_name: string;
    /**
     * Parent Email
     */
    parent_email: string;
    /**
     * Id
     */
    id: string;
    status: RegistrationStatus;
    /**
     * Created At
     */
    created_at?: string | null;
    trip?: TripPublic | null;
};

/**
 * RegistrationStatus
 */
export type RegistrationStatus = 'pending' | 'confirmed' | 'cancelled';

/**
 * RegistrationUpdate
 */
export type RegistrationUpdate = {
    /**
     * Student Name
     */
    student_name?: string | null;
    /**
     * Parent Name
     */
    parent_name?: string | null;
    /**
     * Parent Email
     */
    parent_email?: string | null;
    status?: RegistrationStatus | null;
};

/**
 * RegistrationsPublic
 */
export type RegistrationsPublic = {
    /**
     * Data
     */
    data: Array<RegistrationPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * SchoolCreate
 */
export type SchoolCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Address
     */
    address?: string | null;
};

/**
 * SchoolPublic
 */
export type SchoolPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Address
     */
    address?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * SchoolUpdate
 */
export type SchoolUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Address
     */
    address?: string | null;
};

/**
 * SchoolsPublic
 */
export type SchoolsPublic = {
    /**
     * Data
     */
    data: Array<SchoolPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * TripCreate
 */
export type TripCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Location
     */
    location: string;
    /**
     * Date
     */
    date: string;
    /**
     * Cost
     */
    cost: number | string;
    /**
     * Max Students
     */
    max_students?: number;
    /**
     * School Id
     */
    school_id: string;
};

/**
 * TripPublic
 */
export type TripPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Location
     */
    location: string;
    /**
     * Date
     */
    date: string;
    /**
     * Cost
     */
    cost: string;
    /**
     * Max Students
     */
    max_students?: number;
    /**
     * Id
     */
    id: string;
    /**
     * School Id
     */
    school_id: string;
    /**
     * Registration Count
     */
    registration_count?: number | null;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * TripUpdate
 */
export type TripUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Location
     */
    location?: string | null;
    /**
     * Date
     */
    date?: string | null;
    /**
     * Cost
     */
    cost?: number | string | null;
    /**
     * Max Students
     */
    max_students?: number | null;
};

/**
 * TripsPublic
 */
export type TripsPublic = {
    /**
     * Data
     */
    data: Array<TripPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ReadUsersApiV1UsersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type ReadUsersApiV1UsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUsersApiV1UsersGetError = ReadUsersApiV1UsersGetErrors[keyof ReadUsersApiV1UsersGetErrors];

export type ReadUsersApiV1UsersGetResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type ReadUsersApiV1UsersGetResponse = ReadUsersApiV1UsersGetResponses[keyof ReadUsersApiV1UsersGetResponses];

export type RegisterUserApiV1UsersPostData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type RegisterUserApiV1UsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterUserApiV1UsersPostError = RegisterUserApiV1UsersPostErrors[keyof RegisterUserApiV1UsersPostErrors];

export type RegisterUserApiV1UsersPostResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type RegisterUserApiV1UsersPostResponse = RegisterUserApiV1UsersPostResponses[keyof RegisterUserApiV1UsersPostResponses];

export type DeleteUserMeApiV1UsersMeDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type DeleteUserMeApiV1UsersMeDeleteResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteUserMeApiV1UsersMeDeleteResponse = DeleteUserMeApiV1UsersMeDeleteResponses[keyof DeleteUserMeApiV1UsersMeDeleteResponses];

export type ReadUserMeApiV1UsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type ReadUserMeApiV1UsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type ReadUserMeApiV1UsersMeGetResponse = ReadUserMeApiV1UsersMeGetResponses[keyof ReadUserMeApiV1UsersMeGetResponses];

export type UpdateUserMeApiV1UsersMePatchData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UpdateUserMeApiV1UsersMePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserMeApiV1UsersMePatchError = UpdateUserMeApiV1UsersMePatchErrors[keyof UpdateUserMeApiV1UsersMePatchErrors];

export type UpdateUserMeApiV1UsersMePatchResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UpdateUserMeApiV1UsersMePatchResponse = UpdateUserMeApiV1UsersMePatchResponses[keyof UpdateUserMeApiV1UsersMePatchResponses];

export type UpdatePasswordMeApiV1UsersMePasswordPatchData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UpdatePasswordMeApiV1UsersMePasswordPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePasswordMeApiV1UsersMePasswordPatchError = UpdatePasswordMeApiV1UsersMePasswordPatchErrors[keyof UpdatePasswordMeApiV1UsersMePasswordPatchErrors];

export type UpdatePasswordMeApiV1UsersMePasswordPatchResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UpdatePasswordMeApiV1UsersMePasswordPatchResponse = UpdatePasswordMeApiV1UsersMePasswordPatchResponses[keyof UpdatePasswordMeApiV1UsersMePasswordPatchResponses];

export type DeleteUserApiV1UsersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type DeleteUserApiV1UsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserApiV1UsersUserIdDeleteError = DeleteUserApiV1UsersUserIdDeleteErrors[keyof DeleteUserApiV1UsersUserIdDeleteErrors];

export type DeleteUserApiV1UsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteUserApiV1UsersUserIdDeleteResponse = DeleteUserApiV1UsersUserIdDeleteResponses[keyof DeleteUserApiV1UsersUserIdDeleteResponses];

export type ReadUserByIdApiV1UsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type ReadUserByIdApiV1UsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUserByIdApiV1UsersUserIdGetError = ReadUserByIdApiV1UsersUserIdGetErrors[keyof ReadUserByIdApiV1UsersUserIdGetErrors];

export type ReadUserByIdApiV1UsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type ReadUserByIdApiV1UsersUserIdGetResponse = ReadUserByIdApiV1UsersUserIdGetResponses[keyof ReadUserByIdApiV1UsersUserIdGetResponses];

export type UpdateUserApiV1UsersUserIdPatchData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UpdateUserApiV1UsersUserIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserApiV1UsersUserIdPatchError = UpdateUserApiV1UsersUserIdPatchErrors[keyof UpdateUserApiV1UsersUserIdPatchErrors];

export type UpdateUserApiV1UsersUserIdPatchResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UpdateUserApiV1UsersUserIdPatchResponse = UpdateUserApiV1UsersUserIdPatchResponses[keyof UpdateUserApiV1UsersUserIdPatchResponses];

export type LoginAccessTokenApiV1UsersLoginAccessTokenPostData = {
    body: BodyLoginAccessTokenApiV1UsersLoginAccessTokenPost;
    path?: never;
    query?: never;
    url: '/api/v1/users/login/access-token';
};

export type LoginAccessTokenApiV1UsersLoginAccessTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAccessTokenApiV1UsersLoginAccessTokenPostError = LoginAccessTokenApiV1UsersLoginAccessTokenPostErrors[keyof LoginAccessTokenApiV1UsersLoginAccessTokenPostErrors];

export type LoginAccessTokenApiV1UsersLoginAccessTokenPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginAccessTokenApiV1UsersLoginAccessTokenPostResponse = LoginAccessTokenApiV1UsersLoginAccessTokenPostResponses[keyof LoginAccessTokenApiV1UsersLoginAccessTokenPostResponses];

export type ReadSchoolsApiV1SchoolsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/schools/';
};

export type ReadSchoolsApiV1SchoolsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadSchoolsApiV1SchoolsGetError = ReadSchoolsApiV1SchoolsGetErrors[keyof ReadSchoolsApiV1SchoolsGetErrors];

export type ReadSchoolsApiV1SchoolsGetResponses = {
    /**
     * Successful Response
     */
    200: SchoolsPublic;
};

export type ReadSchoolsApiV1SchoolsGetResponse = ReadSchoolsApiV1SchoolsGetResponses[keyof ReadSchoolsApiV1SchoolsGetResponses];

export type CreateSchoolApiV1SchoolsPostData = {
    body: SchoolCreate;
    path?: never;
    query?: never;
    url: '/api/v1/schools/';
};

export type CreateSchoolApiV1SchoolsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSchoolApiV1SchoolsPostError = CreateSchoolApiV1SchoolsPostErrors[keyof CreateSchoolApiV1SchoolsPostErrors];

export type CreateSchoolApiV1SchoolsPostResponses = {
    /**
     * Successful Response
     */
    200: SchoolPublic;
};

export type CreateSchoolApiV1SchoolsPostResponse = CreateSchoolApiV1SchoolsPostResponses[keyof CreateSchoolApiV1SchoolsPostResponses];

export type DeleteSchoolApiV1SchoolsSchoolIdDeleteData = {
    body?: never;
    path: {
        /**
         * School Id
         */
        school_id: string;
    };
    query?: never;
    url: '/api/v1/schools/{school_id}';
};

export type DeleteSchoolApiV1SchoolsSchoolIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSchoolApiV1SchoolsSchoolIdDeleteError = DeleteSchoolApiV1SchoolsSchoolIdDeleteErrors[keyof DeleteSchoolApiV1SchoolsSchoolIdDeleteErrors];

export type DeleteSchoolApiV1SchoolsSchoolIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteSchoolApiV1SchoolsSchoolIdDeleteResponse = DeleteSchoolApiV1SchoolsSchoolIdDeleteResponses[keyof DeleteSchoolApiV1SchoolsSchoolIdDeleteResponses];

export type ReadSchoolByIdApiV1SchoolsSchoolIdGetData = {
    body?: never;
    path: {
        /**
         * School Id
         */
        school_id: string;
    };
    query?: never;
    url: '/api/v1/schools/{school_id}';
};

export type ReadSchoolByIdApiV1SchoolsSchoolIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadSchoolByIdApiV1SchoolsSchoolIdGetError = ReadSchoolByIdApiV1SchoolsSchoolIdGetErrors[keyof ReadSchoolByIdApiV1SchoolsSchoolIdGetErrors];

export type ReadSchoolByIdApiV1SchoolsSchoolIdGetResponses = {
    /**
     * Successful Response
     */
    200: SchoolPublic;
};

export type ReadSchoolByIdApiV1SchoolsSchoolIdGetResponse = ReadSchoolByIdApiV1SchoolsSchoolIdGetResponses[keyof ReadSchoolByIdApiV1SchoolsSchoolIdGetResponses];

export type UpdateSchoolApiV1SchoolsSchoolIdPatchData = {
    body: SchoolUpdate;
    path: {
        /**
         * School Id
         */
        school_id: string;
    };
    query?: never;
    url: '/api/v1/schools/{school_id}';
};

export type UpdateSchoolApiV1SchoolsSchoolIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSchoolApiV1SchoolsSchoolIdPatchError = UpdateSchoolApiV1SchoolsSchoolIdPatchErrors[keyof UpdateSchoolApiV1SchoolsSchoolIdPatchErrors];

export type UpdateSchoolApiV1SchoolsSchoolIdPatchResponses = {
    /**
     * Successful Response
     */
    200: SchoolPublic;
};

export type UpdateSchoolApiV1SchoolsSchoolIdPatchResponse = UpdateSchoolApiV1SchoolsSchoolIdPatchResponses[keyof UpdateSchoolApiV1SchoolsSchoolIdPatchResponses];

export type ReadTripsApiV1TripsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * School Id
         */
        school_id?: string | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/trips/';
};

export type ReadTripsApiV1TripsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadTripsApiV1TripsGetError = ReadTripsApiV1TripsGetErrors[keyof ReadTripsApiV1TripsGetErrors];

export type ReadTripsApiV1TripsGetResponses = {
    /**
     * Successful Response
     */
    200: TripsPublic;
};

export type ReadTripsApiV1TripsGetResponse = ReadTripsApiV1TripsGetResponses[keyof ReadTripsApiV1TripsGetResponses];

export type CreateTripApiV1TripsPostData = {
    body: TripCreate;
    path?: never;
    query?: never;
    url: '/api/v1/trips/';
};

export type CreateTripApiV1TripsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTripApiV1TripsPostError = CreateTripApiV1TripsPostErrors[keyof CreateTripApiV1TripsPostErrors];

export type CreateTripApiV1TripsPostResponses = {
    /**
     * Successful Response
     */
    200: TripPublic;
};

export type CreateTripApiV1TripsPostResponse = CreateTripApiV1TripsPostResponses[keyof CreateTripApiV1TripsPostResponses];

export type DeleteTripApiV1TripsTripIdDeleteData = {
    body?: never;
    path: {
        /**
         * Trip Id
         */
        trip_id: string;
    };
    query?: never;
    url: '/api/v1/trips/{trip_id}';
};

export type DeleteTripApiV1TripsTripIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTripApiV1TripsTripIdDeleteError = DeleteTripApiV1TripsTripIdDeleteErrors[keyof DeleteTripApiV1TripsTripIdDeleteErrors];

export type DeleteTripApiV1TripsTripIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteTripApiV1TripsTripIdDeleteResponse = DeleteTripApiV1TripsTripIdDeleteResponses[keyof DeleteTripApiV1TripsTripIdDeleteResponses];

export type ReadTripByIdApiV1TripsTripIdGetData = {
    body?: never;
    path: {
        /**
         * Trip Id
         */
        trip_id: string;
    };
    query?: never;
    url: '/api/v1/trips/{trip_id}';
};

export type ReadTripByIdApiV1TripsTripIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadTripByIdApiV1TripsTripIdGetError = ReadTripByIdApiV1TripsTripIdGetErrors[keyof ReadTripByIdApiV1TripsTripIdGetErrors];

export type ReadTripByIdApiV1TripsTripIdGetResponses = {
    /**
     * Successful Response
     */
    200: TripPublic;
};

export type ReadTripByIdApiV1TripsTripIdGetResponse = ReadTripByIdApiV1TripsTripIdGetResponses[keyof ReadTripByIdApiV1TripsTripIdGetResponses];

export type UpdateTripApiV1TripsTripIdPatchData = {
    body: TripUpdate;
    path: {
        /**
         * Trip Id
         */
        trip_id: string;
    };
    query?: never;
    url: '/api/v1/trips/{trip_id}';
};

export type UpdateTripApiV1TripsTripIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTripApiV1TripsTripIdPatchError = UpdateTripApiV1TripsTripIdPatchErrors[keyof UpdateTripApiV1TripsTripIdPatchErrors];

export type UpdateTripApiV1TripsTripIdPatchResponses = {
    /**
     * Successful Response
     */
    200: TripPublic;
};

export type UpdateTripApiV1TripsTripIdPatchResponse = UpdateTripApiV1TripsTripIdPatchResponses[keyof UpdateTripApiV1TripsTripIdPatchResponses];

export type ReadRegistrationsApiV1RegistrationsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Trip Id
         */
        trip_id?: string | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/registrations/';
};

export type ReadRegistrationsApiV1RegistrationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadRegistrationsApiV1RegistrationsGetError = ReadRegistrationsApiV1RegistrationsGetErrors[keyof ReadRegistrationsApiV1RegistrationsGetErrors];

export type ReadRegistrationsApiV1RegistrationsGetResponses = {
    /**
     * Successful Response
     */
    200: RegistrationsPublic;
};

export type ReadRegistrationsApiV1RegistrationsGetResponse = ReadRegistrationsApiV1RegistrationsGetResponses[keyof ReadRegistrationsApiV1RegistrationsGetResponses];

export type CreateRegistrationApiV1RegistrationsPostData = {
    body: RegistrationCreate;
    path?: never;
    query?: never;
    url: '/api/v1/registrations/';
};

export type CreateRegistrationApiV1RegistrationsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRegistrationApiV1RegistrationsPostError = CreateRegistrationApiV1RegistrationsPostErrors[keyof CreateRegistrationApiV1RegistrationsPostErrors];

export type CreateRegistrationApiV1RegistrationsPostResponses = {
    /**
     * Successful Response
     */
    200: RegistrationPublic;
};

export type CreateRegistrationApiV1RegistrationsPostResponse = CreateRegistrationApiV1RegistrationsPostResponses[keyof CreateRegistrationApiV1RegistrationsPostResponses];

export type ReadMyRegistrationsApiV1RegistrationsMeGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/registrations/me';
};

export type ReadMyRegistrationsApiV1RegistrationsMeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadMyRegistrationsApiV1RegistrationsMeGetError = ReadMyRegistrationsApiV1RegistrationsMeGetErrors[keyof ReadMyRegistrationsApiV1RegistrationsMeGetErrors];

export type ReadMyRegistrationsApiV1RegistrationsMeGetResponses = {
    /**
     * Successful Response
     */
    200: RegistrationsPublic;
};

export type ReadMyRegistrationsApiV1RegistrationsMeGetResponse = ReadMyRegistrationsApiV1RegistrationsMeGetResponses[keyof ReadMyRegistrationsApiV1RegistrationsMeGetResponses];

export type DeleteRegistrationApiV1RegistrationsRegistrationIdDeleteData = {
    body?: never;
    path: {
        /**
         * Registration Id
         */
        registration_id: string;
    };
    query?: never;
    url: '/api/v1/registrations/{registration_id}';
};

export type DeleteRegistrationApiV1RegistrationsRegistrationIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRegistrationApiV1RegistrationsRegistrationIdDeleteError = DeleteRegistrationApiV1RegistrationsRegistrationIdDeleteErrors[keyof DeleteRegistrationApiV1RegistrationsRegistrationIdDeleteErrors];

export type DeleteRegistrationApiV1RegistrationsRegistrationIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteRegistrationApiV1RegistrationsRegistrationIdDeleteResponse = DeleteRegistrationApiV1RegistrationsRegistrationIdDeleteResponses[keyof DeleteRegistrationApiV1RegistrationsRegistrationIdDeleteResponses];

export type ReadRegistrationByIdApiV1RegistrationsRegistrationIdGetData = {
    body?: never;
    path: {
        /**
         * Registration Id
         */
        registration_id: string;
    };
    query?: never;
    url: '/api/v1/registrations/{registration_id}';
};

export type ReadRegistrationByIdApiV1RegistrationsRegistrationIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadRegistrationByIdApiV1RegistrationsRegistrationIdGetError = ReadRegistrationByIdApiV1RegistrationsRegistrationIdGetErrors[keyof ReadRegistrationByIdApiV1RegistrationsRegistrationIdGetErrors];

export type ReadRegistrationByIdApiV1RegistrationsRegistrationIdGetResponses = {
    /**
     * Successful Response
     */
    200: RegistrationPublic;
};

export type ReadRegistrationByIdApiV1RegistrationsRegistrationIdGetResponse = ReadRegistrationByIdApiV1RegistrationsRegistrationIdGetResponses[keyof ReadRegistrationByIdApiV1RegistrationsRegistrationIdGetResponses];

export type UpdateRegistrationApiV1RegistrationsRegistrationIdPatchData = {
    body: RegistrationUpdate;
    path: {
        /**
         * Registration Id
         */
        registration_id: string;
    };
    query?: never;
    url: '/api/v1/registrations/{registration_id}';
};

export type UpdateRegistrationApiV1RegistrationsRegistrationIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateRegistrationApiV1RegistrationsRegistrationIdPatchError = UpdateRegistrationApiV1RegistrationsRegistrationIdPatchErrors[keyof UpdateRegistrationApiV1RegistrationsRegistrationIdPatchErrors];

export type UpdateRegistrationApiV1RegistrationsRegistrationIdPatchResponses = {
    /**
     * Successful Response
     */
    200: RegistrationPublic;
};

export type UpdateRegistrationApiV1RegistrationsRegistrationIdPatchResponse = UpdateRegistrationApiV1RegistrationsRegistrationIdPatchResponses[keyof UpdateRegistrationApiV1RegistrationsRegistrationIdPatchResponses];

export type SubmitPaymentApiV1PaymentsPostData = {
    body: PaymentProcess;
    path?: never;
    query?: never;
    url: '/api/v1/payments/';
};

export type SubmitPaymentApiV1PaymentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitPaymentApiV1PaymentsPostError = SubmitPaymentApiV1PaymentsPostErrors[keyof SubmitPaymentApiV1PaymentsPostErrors];

export type SubmitPaymentApiV1PaymentsPostResponses = {
    /**
     * Successful Response
     */
    200: PaymentPublic;
};

export type SubmitPaymentApiV1PaymentsPostResponse = SubmitPaymentApiV1PaymentsPostResponses[keyof SubmitPaymentApiV1PaymentsPostResponses];

export type ReadPaymentByIdApiV1PaymentsPaymentIdGetData = {
    body?: never;
    path: {
        /**
         * Payment Id
         */
        payment_id: string;
    };
    query?: never;
    url: '/api/v1/payments/{payment_id}';
};

export type ReadPaymentByIdApiV1PaymentsPaymentIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadPaymentByIdApiV1PaymentsPaymentIdGetError = ReadPaymentByIdApiV1PaymentsPaymentIdGetErrors[keyof ReadPaymentByIdApiV1PaymentsPaymentIdGetErrors];

export type ReadPaymentByIdApiV1PaymentsPaymentIdGetResponses = {
    /**
     * Successful Response
     */
    200: PaymentPublic;
};

export type ReadPaymentByIdApiV1PaymentsPaymentIdGetResponse = ReadPaymentByIdApiV1PaymentsPaymentIdGetResponses[keyof ReadPaymentByIdApiV1PaymentsPaymentIdGetResponses];
